[[constraint]]
  name = "github.com/containers/image"
  branch = "master"

# vendor/github.com/docker/go-metrics/timer.go:39:4: undefined: prometheus.Observer
[[override]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.0-pre1"

[prune]
  go-tests = true
  unused-packages = true
